name: 'Demo Reusable Job'

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:
  reusable_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run a reusable script
        run: echo Hey, ${{ inputs.username }}